keys: &keys
  - age15hhcucut5p5pm9hzpjs6lrjsnwc7ccgsqr6hwed5f77clkpecdcstzy2z3 # laptop system
  - age1f9cclgyjmf2693amgxh8jjl3x7vkd3c6h6grqtutcz4fvd4d5ghsrlcyg3 # laptop user
  - age1k3u6sze67cqywgcecg4k8qg9en9sv7vahclp53800kqv86eyralq9va3f0 # desktop system
  - age15cnz2zzya20ya8hejdakpem9vr59jvjzr880h68eta8366m8tg5sm2566k # desktop user
creation_rules:
  - path_regex: ^secrets\.yaml$
    key_groups:
      - age: *keys
