#!/usr/bin/env bash
#                       
#    __ _ ___ _ __ ___  
#   / _` / __| '_ ` _ \ 
#  | (_| \__ \ | | | | |
#   \__,_|___/_| |_| |_|
#                       

. sclib

scset "SCERR"
. scinit


if [ "$#" = 0 ]; then
    scfatal "expected at least 1 argument"
fi

if [ "$#" = 1 ]; then
    RUN=0
    FILE="$1"
else
    if [ "$1" = "-r" ]; then
        RUN=1
        FILE="$2"
    elif [ "$2" = "-r" ]; then
        RUN=1
        FILE="$1"
    else
        scfatal "invalid arguments"
    fi
fi
    

if ! [ -f "$FILE" ]; then
    scfatal "target $FILE does not exist"
fi

nasm -felf64 "$FILE" # assemble
ld -o "${FILE%.*}" "${FILE%.*}.o" # link

if [ "$RUN" = 1 ]; then
    ./"${FILE%.*}"
fi

