#!/usr/bin/env bash


. sclib

scset "SCERR"
. scinit


if command -v apt-fast &> /dev/null; then
	APTCMD="apt-fast"
fi

if command -v apt &> /dev/null; then
	APTCMD="apt"
fi


if command -v update-dotfiles &> /dev/null; then
	update-dotfiles
fi


if isset $APTCMD; then
	sudo $APTCMD update -y
	sudo $APTCMD full-upgrade -y
	sudo $APTCMD autoremove -y
	sudo $APTCMD clean -y
	sudo $APTCMD autoclean -y
fi


if command -v xbps-install &> /dev/null; then
	sudo xbps-install -Suy
fi


if command -v flatpak &> /dev/null; then
	sudo flatpak update -y
fi


if command -v npm &> /dev/null; then
	sudo npm update -g --no-audit --no-fund
fi


if command -v pnpm &> /dev/null; then
	pnpm update -g
fi


if command -v update-nvim &> /dev/null; then
	update-nvim
fi

