#!/usr/bin/env bash


. sclib
. scinit


sudo true


 echo -e "\033[35mUpdating configuration...\033[0m"

if command -v update-dotfiles &> /dev/null; then
	update-dotfiles
fi

echo;


if command -v update-packages &> /dev/null; then
	update-packages
fi


 echo -e "\n\033[35mUpdating neovim plugins...\033[0m"
if command -v update-nvim &> /dev/null; then
	update-nvim
fi

