#!/usr/bin/env bash


sudo true


echo -e "\033[35mChecking for package managers\033[0m"


package_managers=("apt-fast" "apt" "xbps-install" "npm" "pnpm" "flatpak")
available_package_managers=()


for pm in "${package_managers[@]}"; do
    if command -v "$pm" &> /dev/null; then
        echo -e "\e[32m✔\e[0m $pm"
        available_package_managers+=("$pm")
    else
        echo -e "\e[31m✘\e[0m $pm"
    fi
done


for pm in "${available_package_managers[@]}"; do
    echo -e "\n\033[35mUpdating packages using $pm...\033[0m"
    case "$pm" in
        "apt-fast")
            sudo apt-fast update && sudo apt-fast upgrade -y
            sudo apt-fast autoremove -y
            sudo apt-fast clean -y
            ;;
        "apt")
            sudo apt update && sudo apt upgrade -y
            sudo apt autoremove -y
            sudo apt clean -y
            ;;
        "xbps-install")
            sudo xbps-install -Suy
            ;;
        "npm")
            sudo npm update -g
            ;;
        "pnpm")
            sudo pnpm update -g
            pnpm update -g
            ;;
        "flatpak")
            sudo flatpak update -y
            ;;
    esac
done

