#!/usr/bin/env bash


. sclib

scset "SCERR"
. scinit


sudo true


if command -v update-dotfiles &> /dev/null; then
	update-dotfiles
fi


if command -v update-packages &> /dev/null; then
	update-packages
fi


if command -v update-nvim &> /dev/null; then
	update-nvim
fi

